// THIS FILE IS AUTO GENERATED: DO NOT EDIT THIS FILE DIRECTLY
// This is the shared Vitest configuration for the monorepo
// Package-specific configs should import and extend this

import { defineConfig } from "vitest/config";
import type { UserConfig } from "vitest/config";

export interface VitestConfigOptions {
    projectName: string;
    setupFiles?: string[];
}

export function createVitestConfig(options: VitestConfigOptions): UserConfig {
    return defineConfig({
        test: {
            globals: true,
            environment: "happy-dom",
            setupFiles: options.setupFiles,
            coverage: {
                provider: "v8",
                reporter: ["text", "json", "html", "lcov"],
                exclude: ["node_modules", "dist", "**/*.d.ts", "**/*.config.*", "**/mockData", "**/__tests__"],
                thresholds: {
                    lines: 80,
                    functions: 80,
                    branches: 75,
                    statements: 80,
                },
            },
            reporters: ["default"],
            testTimeout: 30000,
        },
    });
}
